### PR TITLE
Add siteurl if not full url

### PR DESCRIPTION
**Pull request by fank**
This is how a channel description looks like currently:
```
[url=https://example.com/category/5/arma-iii][img]/assets/uploads/category/category-5.png[/img][/url]
```

And than:
```
[url=https://example.com/category/5/arma-iii][img]https://example.com/assets/uploads/category/category-5.png[/img][/url]
```

### CODE REVIEW

**Comment by WarbleSync** [comment]
Nice work. Thanks! 😊

**Comment by fank** [comment]
Could you please publish a new version with this change?

**Comment by WarbleSync** [comment]
Yes but I think the is another pull so I'll try and get that in as well.

**Comment by WarbleSync** [comment]
new version is up

**Pull request merged**
